export interface ComponentEntry {
  slug: string;
  title: string;
  description: string;
}

export const components: ComponentEntry[] = [
  { slug: 'accordion', title: 'Accordion', description: 'A vertically stacked set of interactive headings that each reveal a section of content.' },
  { slug: 'alert', title: 'Alert', description: 'Displays a callout for user attention.' },
  { slug: 'alert-dialog', title: 'Alert Dialog', description: 'A modal dialog that interrupts the user with important content and expects a response.' },
  { slug: 'aspect-ratio', title: 'Aspect Ratio', description: 'Displays content within a desired ratio.' },
  { slug: 'avatar', title: 'Avatar', description: 'An image element with a fallback for representing the user.' },
  { slug: 'badge', title: 'Badge', description: 'Displays a badge or a component that looks like a badge.' },
  { slug: 'breadcrumb', title: 'Breadcrumb', description: 'Displays the path to the current resource using a hierarchy of links.' },
  { slug: 'button', title: 'Button', description: 'Displays a button or a component that looks like a button.' },
  { slug: 'calendar', title: 'Calendar', description: 'A date field component that allows users to enter and edit dates.' },
  { slug: 'card', title: 'Card', description: 'Displays a card with header, content, and footer.' },
  { slug: 'carousel', title: 'Carousel', description: 'A carousel with motion and swipe built using Embla.' },
  { slug: 'chart', title: 'Chart', description: 'Beautiful charts built using Recharts.' },
  { slug: 'checkbox', title: 'Checkbox', description: 'A control that allows the user to toggle between checked and not checked.' },
  { slug: 'collapsible', title: 'Collapsible', description: 'An interactive component which expands/collapses a panel.' },
  { slug: 'command', title: 'Command', description: 'Fast, composable command menu built with cmdk.' },
  { slug: 'context-menu', title: 'Context Menu', description: 'Displays a menu located at the pointer, triggered by right-click.' },
  { slug: 'dialog', title: 'Dialog', description: 'A window overlaid on the primary window, rendering the content underneath inert.' },
  { slug: 'drawer', title: 'Drawer', description: 'A drawer component built on top of Vaul.' },
  { slug: 'dropdown-menu', title: 'Dropdown Menu', description: 'Displays a menu of actions or functions triggered by a button.' },
  { slug: 'hover-card', title: 'Hover Card', description: 'For sighted users to preview content available behind a link.' },
  { slug: 'input', title: 'Input', description: 'Displays a form input field.' },
  { slug: 'input-otp', title: 'Input OTP', description: 'Accessible one-time password input with copy-paste functionality.' },
  { slug: 'label', title: 'Label', description: 'Renders an accessible label associated with controls.' },
  { slug: 'menubar', title: 'Menubar', description: 'A visually persistent menu common in desktop applications.' },
  { slug: 'navigation-menu', title: 'Navigation Menu', description: 'A collection of links for navigating websites.' },
  { slug: 'pagination', title: 'Pagination', description: 'Pagination with page navigation, next and previous links.' },
  { slug: 'popover', title: 'Popover', description: 'Displays rich content in a portal, triggered by a button.' },
  { slug: 'progress', title: 'Progress', description: 'Displays an indicator showing the completion progress of a task.' },
  { slug: 'radio-group', title: 'Radio Group', description: 'A set of checkable buttons where only one can be checked at a time.' },
  { slug: 'resizable', title: 'Resizable', description: 'Accessible resizable panel groups and layouts.' },
  { slug: 'scroll-area', title: 'Scroll Area', description: 'Augments native scroll functionality for custom, cross-browser styling.' },
  { slug: 'select', title: 'Select', description: 'Displays a list of options for the user to pick from, triggered by a button.' },
  { slug: 'separator', title: 'Separator', description: 'Visually or semantically separates content.' },
  { slug: 'sheet', title: 'Sheet', description: 'Extends the Dialog component to display content complementary to the main screen.' },
  { slug: 'sidebar', title: 'Sidebar', description: 'A composable, themeable and customizable sidebar component.' },
  { slug: 'skeleton', title: 'Skeleton', description: 'Use to show a placeholder while content is loading.' },
  { slug: 'slider', title: 'Slider', description: 'An input where the user selects a value from within a given range.' },
  { slug: 'sonner', title: 'Sonner', description: 'An opinionated toast component for React.' },
  { slug: 'switch', title: 'Switch', description: 'A control that allows the user to toggle between on and off.' },
  { slug: 'table', title: 'Table', description: 'A responsive table component.' },
  { slug: 'tabs', title: 'Tabs', description: 'A set of layered sections of content displayed one at a time.' },
  { slug: 'textarea', title: 'Textarea', description: 'Displays a form textarea field.' },
  { slug: 'toggle', title: 'Toggle', description: 'A two-state button that can be either on or off.' },
  { slug: 'toggle-group', title: 'Toggle Group', description: 'A set of two-state buttons that can be toggled on or off.' },
  { slug: 'tooltip', title: 'Tooltip', description: 'A popup that displays information related to an element on hover or focus.' },
];
